# Generated by Django 6.0.1 on 2026-02-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["-departure_time"]},
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["route", "departure_time"],
                name="airport_fli_route_i_baa295_idx",
            ),
        ),
    ]
