# Generated by Django 6.0.1 on 2026-02-23 15:12

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_flight_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
